version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: '<Admin Password>'
      DNS1: 10.30.0.3
      DNS2: 10.30.0.3
      ServerIP: <Host IP>
    dns:
      - 127.0.0.1
      - 10.30.0.3
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    depends_on:
     - dnscrypt-proxy
    networks:
      pihole:
        ipv4_address: 10.30.0.2

  dnscrypt-proxy:
    container_name: dnscrypt-proxy
    image: imple/dnscrypt-proxy:latest
    restart: unless-stopped
    networks:
      pihole:
        ipv4_address: 10.30.0.3

networks:
  pihole:
    ipam:
      config:
        - subnet: 10.30.0.0/24
